name: Build Static FFmpeg on Windows

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-static-ffmpeg:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-crt-git
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gdb
          mingw-w64-x86_64-gdb-multiarch
          mingw-w64-x86_64-headers-git
          mingw-w64-x86_64-libmangle-git
          mingw-w64-x86_64-libwinpthread
          mingw-w64-x86_64-make
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-tools-git
          mingw-w64-x86_64-winpthreads
          mingw-w64-x86_64-winstorecompat-git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-yasm
          mingw-w64-x86_64-nasm
          autoconf
          automake
          libtool
          unzip

    - name: Build static dependencies
      shell: msys2 {0}
      run: |
        mkdir -p /mingw64/static
        cd /mingw64/static

        # Build x264
        git clone --depth 1 https://code.videolan.org/videolan/x264.git
        cd x264 && ./configure --prefix=/mingw64/static --enable-static --disable-cli && make -j$(nproc) && make install
        cd ..

        # Build x265
        git clone --depth 1 https://github.com/videolan/x265.git
        cd x265/build/linux && cmake -G "Unix Makefiles" -DENABLE_SHARED=OFF -DCMAKE_INSTALL_PREFIX=/mingw64/static ../../source && make -j$(nproc) && make install
        cd ../../../

        # Build fdk-aac
        git clone --depth 1 https://github.com/mstorsjo/fdk-aac.git
        cd fdk-aac && ./autogen.sh && ./configure --prefix=/mingw64/static --enable-static --disable-shared && make -j$(nproc) && make install
        cd ..

        # Build openh264
        git clone --depth 1 https://github.com/cisco/openh264.git
        cd openh264 && make -j$(nproc) ENABLE_STATIC=Yes && make install PREFIX=/mingw64/static
        cd ..

        # Build libvpx
        git clone --depth 1 https://chromium.googlesource.com/webm/libvpx
        cd libvpx && ./configure --prefix=/mingw64/static --disable-examples --disable-tools --disable-docs --enable-static --disable-shared && make -j$(nproc) && make install
        cd ..

        # Build mp3lame
        curl -LO https://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz
        tar -xzf lame-3.99.5.tar.gz && cd lame-3.99.5 && ./configure --prefix=/mingw64/static --enable-static --disable-shared && make -j$(nproc) && make install
        cd ..

        # Build libass (with dependencies)
        pacman -S --noconfirm mingw-w64-x86_64-fontconfig mingw-w64-x86_64-freetype mingw-w64-x86_64-fribidi
        git clone --depth 1 https://github.com/libass/libass.git
        cd libass && ./autogen.sh && ./configure --prefix=/mingw64/static --enable-static --disable-shared && make -j$(nproc) && make install
        cd ..

    - name: Build FFmpeg static
      shell: msys2 {0}
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg && cd ffmpeg

        PKG_CONFIG_PATH=/mingw64/static/lib/pkgconfig \
        ./configure \
          --prefix=/mingw64/ffmpeg-build \
          --pkg-config-flags="--static" \
          --extra-cflags="-I/mingw64/static/include" \
          --extra-ldflags="-L/mingw64/static/lib" \
          --extra-libs="-lm -lpthread" \
          --enable-gpl --enable-version3 --enable-nonfree \
          --enable-static --disable-shared \
          --enable-libx264 --enable-libx265 \
          --enable-libfdk_aac --enable-libopenh264 \
          --enable-libmp3lame --enable-libopus \
          --enable-libvpx --enable-libass \
          --disable-debug --disable-doc --disable-ffplay

        make -j$(nproc)
        make install

    - name: Package build
      shell: msys2 {0}
      run: |
        cd /mingw64/ffmpeg-build/bin
        zip -r /c/Users/runneradmin/ffmpeg-static.zip *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-win-static
        path: C:\Users\runneradmin\ffmpeg-static.zip
