name: Build Ultimate Static Windows FFmpeg with MSYS2 GCC/Clang

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

env:
  # Global build configuration
  BUILD_PREFIX: /d/ffmpeg-build
  CLANG_PREFIX: /d/ffmpeg-build-clang

jobs:
  windows-x86_64-build:
    uses: ./.github/workflows/win.yml
  # Job 3: Create Release (depends on both builds)
  create-release:
    runs-on: ubuntu-latest
    needs: [windows-x86_64-build]
    if: github.event_name == 'schedule' && success()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download GCC build artifact
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts/

    - name: Create Git Tag
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git tag ${{ needs.windows-x86_64-build.outputs.tag_name }}
        git push origin ${{ needs.windows-x86_64-build.outputs.tag_name }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.windows-x86_64-build.outputs.tag_name }}
        name: ${{ needs.windows-x86_64-build.outputs.release_name }}
        files: |
          ./artifacts/ffmpeg-win64-gcc-msvcrt-static.zip
          ./artifacts/ffmpeg-win64-clang-msvcrt-static.zip
          ./artifacts/ffmpeg-win64-gcc-ucrt-static.zip
          ./artifacts/ffmpeg-win64-clang-ucrt-static.zip
        body: |
          ## Automated FFmpeg Builds - Dual Compiler Support
          
          This release includes **two optimized builds** of FFmpeg with comprehensive codec support:
          
          ### 🔧 Available Builds:
          
          #### **GCC Build** (`ffmpeg-win64-gcc-static.zip`)
          - **Compiler**: GCC (MinGW-w64)
          - **Optimization**: `-O2` (Fast compilation, stable)
          - **Size**: Standard
          - **Recommended for**: General use, maximum compatibility
          
          #### **Clang LTO Build** (`ffmpeg-win64-clang-lto-static.zip`)  
          - **Compiler**: Clang/LLVM
          - **Optimization**: `-O3` with **Thin LTO** (Link Time Optimization)
          - **Linker**: LLD with LTO optimizations
          - **Size**: Smaller and potentially faster
          - **Recommended for**: Performance-critical applications
          
          ### 📋 Features Included (Both Builds):
          - **Video Codecs**: 
            - H.264 (x264), H.265 (x265)  
            - AV1 (SVT-AV1, rav1e, libaom, dav1d)
            - VP8/VP9 (libvpx)
            - VVC/H.266 (VVenC/VVdeC) 
            - MPEG-5 (XEVE/XEVD)
          - **Audio Codecs**: MP3 (LAME), Opus, Vorbis, FLAC, AAC
          - **Hardware Acceleration**: 
            - NVIDIA (NVENC/NVDEC, CUDA)
            - Intel (VPL/QSV)
            - AMD (AMF)
            - Microsoft (DXVA2, D3D11VA)
          - **Text Rendering**: libass with FreeType and HarfBuzz
          - **Static Linking**: No external dependencies required
          
          ### 🚀 Performance Comparison:
          The **Clang LTO build** typically offers:
          - 5-15% smaller binary size
          - 2-8% faster encoding performance
          - Better optimization across library boundaries
          - Longer compile time but runtime benefits
          
          ### 💾 Usage:
          1. Choose your preferred build (GCC for compatibility, Clang LTO for performance)
          2. Download and extract the zip file
          3. Run `ffmpeg.exe` from command line
          4. All required DLLs are included in both packages
          
          ### 🔍 Build Information:
          - **Build Date**: ${{ needs.build-ffmpeg-gcc.outputs.tag_name }}
          - **FFmpeg Version**: Latest git master
          - **Windows Compatibility**: Windows 7+ (64-bit)
          - **Static Linking**: Yes (portable, no installation required)
          
          ---
          
          **Note**: Both builds are functionally identical and support the same features. The choice between GCC and Clang LTO is based on your performance vs. compatibility preferences.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job 4: Performance Benchmarking (Optional)
  benchmark:
    runs-on: windows-latest
    needs: [windows-x86_64-build]
    if: github.event_name == 'workflow_dispatch'  # Only run on manual trigger
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download both builds
      uses: actions/download-artifact@v4
      with:
        path: ./builds/

    - name: Setup benchmark environment
      shell: powershell
      run: |
        # Extract both builds
        Expand-Archive -Path "./builds/ffmpeg-win64-gcc-static/ffmpeg-win64-gcc-static.zip" -DestinationPath "$env:GITHUB_WORKSPACE/gcc-build"
        Expand-Archive -Path "./builds/ffmpeg-win64-clang-lto-static/ffmpeg-win64-clang-lto-static.zip" -DestinationPath "$env:GITHUB_WORKSPACE/clang-build"
    
        # Create test video in GitHub workspace
        $testFile = Join-Path $env:GITHUB_WORKSPACE "test_input.mp4"
        & "$env:GITHUB_WORKSPACE/gcc-build/bin/ffmpeg.exe" -f lavfi -i "testsrc2=duration=30:size=1920x1080:rate=25" -c:v libx264 -preset medium -crf 23 -y $testFile

    - name: Run encoding benchmarks
      shell: powershell
      run: |
        Write-Host "=== Binary Size Comparison ==="
        $inputFile = Join-Path $env:GITHUB_WORKSPACE "test_input.mp4"
        $gccFFmpeg = Join-Path $env:GITHUB_WORKSPACE "gcc-build/bin/ffmpeg.exe"
        $clangFFmpeg = Join-Path $env:GITHUB_WORKSPACE "clang-build/bin/ffmpeg.exe"
        
        if (-not (Test-Path $inputFile)) { Write-Error "Test input file not found"; exit 1 }
        
        $gccSize = (Get-Item $gccFFmpeg).Length
        $clangSize = (Get-Item $clangFFmpeg).Length
        Write-Host "GCC Build:   $([math]::Round($gccSize/1MB, 2)) MB"
        Write-Host "Clang Build: $([math]::Round($clangSize/1MB, 2)) MB"
        Write-Host "Size Reduction: $([math]::Round((($gccSize - $clangSize)/$gccSize)*100, 2))%"
        
        Write-Host "`n=== Performance Benchmarks ==="
        
        # H.264
        Write-Host "H.264 Encoding Test (x264)..."
        $gccTime = Measure-Command { & $gccFFmpeg -i $inputFile -c:v libx264 -preset medium -crf 23 -f null - -y }
        $clangTime = Measure-Command { & $clangFFmpeg -i $inputFile -c:v libx264 -preset medium -crf 23 -f null - -y }
        Write-Host "GCC Time: $([math]::Round($gccTime.TotalSeconds, 2))s"
        Write-Host "Clang Time: $([math]::Round($clangTime.TotalSeconds, 2))s"
        Write-Host "Performance Improvement: $([math]::Round((($gccTime.TotalSeconds - $clangTime.TotalSeconds)/$gccTime.TotalSeconds)*100, 2))%"
        
        # H.265
        Write-Host "`nH.265 Encoding Test (x265)..."
        $gccTime265 = Measure-Command { & $gccFFmpeg -i $inputFile -c:v libx265 -preset medium -crf 28 -f null - -y }
        $clangTime265 = Measure-Command { & $clangFFmpeg -i $inputFile -c:v libx265 -preset medium -crf 28 -f null - -y }
        Write-Host "GCC Time: $([math]::Round($gccTime265.TotalSeconds, 2))s"
        Write-Host "Clang Time: $([math]::Round($clangTime265.TotalSeconds, 2))s"
        Write-Host "Performance Improvement: $([math]::Round((($gccTime265.TotalSeconds - $clangTime265.TotalSeconds)/$gccTime265.TotalSeconds)*100, 2))%"

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: |
          ./gcc-build/BUILD_INFO.txt
          ./clang-build/BUILD_INFO.txt
        retention-days: 30
